### ISSUE TITLE
Windows 10 - screen won't expand large enough

### ISSUE THREAD

**Issue by dmccallie** [RMcDOttawa/pySkyDarks3#2]
I might be doing something wrong, but on an up to date Windows 10 device, when I launch the app, the main window comes up too small, so the text and controls are jumbled together. The window has a "grow" marker in the lower right corner, but the window does not respond to track pad click-and-drag motions. I tried with a mouse, and that didn't work either. The exposed controls work fine, and the app can connect to TSX just fine.

--david

![image](https://user-images.githubusercontent.com/12226567/73233125-3245a880-414b-11ea-88bf-0a356562ded8.png)

**Comment by dmccallie** [comment]
It might be related to this?  The main window has a maximum size set to 800x600? I don't have it running locally, so I can't test (yet)

  <property name="maximumSize">
   <size>
    <width>800</width>
    <height>600</height>
   </size>
  </property>

**Comment by RMcDOttawa** [comment]
Hi Dave.  Thanks for the info.  That's certainly odd - it doesn't behave that way on other systems I have access to.  I'll see if I can reproduce it.  From the screen shot you sent (thanks) the problem seems to be that the headings' font size has gone way too large - the actual window size looks about right.

I'll try producing a patched version with a resizeable window and with smaller headings, if you'd be willing to try it.  Standby for that.   

- Richard

**Comment by RMcDOttawa** [comment]
HI Dave. Would you mind trying the following, and see how it behaves on your system?  I haven't been able to reproduce the problem you displayed here. 
 
    https://www.dropbox.com/s/yrke578j4nav8cg/pySkyDarks3.exe.zip?dl=0

This version has slightly smaller title fonts, and the window is resizeable.  If you find a window size that works well, it is also remembered for subsequent runs.  You can inspect the change in GitHub.  Let me know how it looks.  Then I'll update on GitHub as a patched release. 

Thanks,  
    Richard

**Comment by RMcDOttawa** [comment]
In fact, while I'm bothering you, would you also try this one:

    https://www.dropbox.com/s/kc8qxu79zwirka8/attempt2.exe.zip?dl=0

Just look at the first tab, as I haven't changed the others.  This is an attempt to get "title sized" titles back, but have them stay in the right scale by basing them on the system font size in use.  Let me know how it appears.

Thank you again,
   Richard

**Comment by dmccallie** [comment]
Here's what the second file (attempt2.exe) looks like, just after opening for the first time:

![image](https://user-images.githubusercontent.com/12226567/73298193-8051bf00-41d2-11ea-88fc-58d1963419d2.png)

And here's what the first tab looks like:

![image](https://user-images.githubusercontent.com/12226567/73298304-aecf9a00-41d2-11ea-9f70-5a4ddca1f4a9.png)

Resizing also now works (to move controls around.)

The default size and font combinations are not quite correct yet in a few other places, though you may not have touched that code yet. For example - the batch add dialog.

![image](https://user-images.githubusercontent.com/12226567/73298765-88f6c500-41d3-11ea-8a06-698ba8b2a6f0.png)

One minor point - the default fonts are pretty tiny on my 17-inch screen. My eyes aren't great, and ideally I would be able to increase the font size by 2 points, even if that required a resize to make things fit. It's certainly usable as is, but it's a strain for my eyes. Windows is very confusing about system font settings - not nearly as nice as the Mac!

**Comment by dmccallie** [comment]
One more comment - when I look at the pasted images above, the fonts appear much larger than they appear on the actual screen. The above sizes are great for my eyes, but the screen sizes are significantly smaller. Strange...

**Comment by RMcDOttawa** [comment]
Thanks, David - I appreciate you taking the time to test this and provide the feedback.  Yes, in the trial version I sent you only the first tab ("Start/End") was recoded, so it's no surprise that the others didn't clean up.  I'll now issue a minor release where that same method is used in all the tabs.  So that will have the resizeable window and the smaller fonts - but it will also still have the "too small" fonts.

Then, for a next release, I'll see about either providing a font size setting in the program, or picking up font size info from the Windows settings (don't know where or how to do that - so a menu option is more likely).  

(I agree it's cleaner on the Mac, and I use the Mac version myself, which I guess is why I was caught by surprise by the strange behaviour on windows.)

**Comment by RMcDOttawa** [comment]
Release 1.0.1 published, which applies that font size unification to all the tabs.  Font size adjustment to follow.
- Richard

**Comment by RMcDOttawa** [comment]
v-1.0.2, just released, is legibility features.  All the windows are now resizeable, and there is a Font menu that can increase or decrease the text size in the windows.  Window and font size settings are remembered.  Hopefully you can tune the font and window-size settings to a good balance of legibility and screen real estate.   Regards,  Richard.
